name: Build‑Train‑Docker‑CI

on: [push]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-a3

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Train and export artifacts
      run: python src/train.py

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Smoke‑test container
      run: docker run --rm $IMAGE_NAME:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}
        docker push $IMAGE_NAME:latest
